
# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8200
  servlet:
    # 应用的访问路径
    context-path: /report/api

# 日志配置
logging:
  level:
    com.ruoyi: debug
    org.springframework: warn

# 用户配置
user:
  password:
    # 密码最大错误次数
    maxRetryCount: 5
    # 密码锁定时间（默认10分钟）
    lockTime: 10

# Spring配置
spring:
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  profiles: 
    active: dev
  # 文件上传
  servlet:
     multipart:
       # 单个文件大小
       max-file-size:  10MB
       # 设置总上传的文件大小
       max-request-size:  20MB


# token配置
token:
    # 令牌自定义标识
    header: Authorization
    # 令牌密钥
    secret: abcdefghijklmnopqrstuvwxyz
    # 令牌有效期（默认30分钟）
    expireTime: 30

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.report.**.domain,com.report.**.dto
  executor-type: simple
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    auto-mapping-unknown-column-behavior: none
    # 一级缓存
    local-cache-scope: session
    # 二级缓存
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  global-config:
    banner: false
    db-config:
      id-type: assign_id
      # 默认值 不建议改
      insert-strategy: not_null
      update-strategy: not_null

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  pageSizeZero: true
  supportMethodsArguments: true
  params: count=countSql


